Pass output stream from probe
palantir/cassandra pull request #528
Opened 2024-08-25 22:32 UTC by wi11dey

So that it can be reliably redirected for nodetool commands to a different buffer, without intercepting any unwanted logs

Full backport of https://github.com/apache/cassandra/commit/83e1e9e45193322f18f57aa7cc4ad31d9d5a152d

2024-08-26 14:36 UTC, inespot approved these changes
For rc

2024-08-27 17:58 UTC, rhuffy commented on src/java/org/apache/cassandra/tools/NodeProbe.java
> +import net.nicoulaj.compilecommand.annotations.Print;
unused import

2024-08-27 18:08 UTC, rhuffy commented
Why not backport everything instead of a partial backport? Excluding the files that don't exist of course. I think the only parts missing are the inner interface `NodeToolCmdRunnable` and `Output.java`

2024-08-27 18:17 UTC, rhuffy commented on src/java/org/apache/cassandra/tools/NodeProbe.java
> +    public NodeProbe(String host, int port, String username, String password, PrintStream output) throws IOException
Can we avoid breaking the constructor API here? The oss patch gets around this with the `setOutput` method
https://github.com/apache/cassandra/commit/83e1e9e45193322f18f57aa7cc4ad31d9d5a152d#diff-92f8748902f03f37a4f7db56b4dfb7d226adcf3839141e6adb8ebbc575020d57R277

2024-08-27 18:21 UTC, rhuffy requested changes
I would prefer if we just backported the patch you linked in the description, specifically to avoid adding a new NodeProbe constructor. I don't want to rely on a custom constructor as this would break forward compatibility in our internal repo.

2024-08-27 20:28 UTC, rhuffy approved these changes

2024-08-27 20:29 UTC, merged